Algoritmo "questao19"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
ano, idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Ano de nascimento: ")
leia(ano)
idade <- 2025 - ano

se idade > 17 entao
   escreva("Maior de idade")
senao
     escreva("Menor de idade")
fimse

Fimalgoritmo