Algoritmo "questao16"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Numero: ")
leia(numero)

se (numero % 2 = 0) e (numero % 3 = 0) entao
   escreva("Divisível por 2 e 3")
senao
    escreva("Não divisível por 2 e 3")
fimse

Fimalgoritmo