Algoritmo "questao11"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
senha: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Senha: ")
leia(senha)

se senha = "1234" entao
    escreva("Acesso permitido")
senao
    escreva("Acesso negado")
fimse

Fimalgoritmo