Algoritmo "questao20"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
valor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe o valor: ")
leia(valor)

se valor >= 100 entao
   valor <- valor * 0.90
   escreva(valor)
senao
    escreva(valor)
fimse

Fimalgoritmo