Algoritmo "questao2"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe o número: ")
leia(numero)

se numero%2 = 0 entao
   escreva(numero, " é par")
senao
     escreva(numero, " é ímpar")
fimse

Fimalgoritmo