Algoritmo "questao9"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe a idade: ")
leia(idade)

se idade > 15 entao
    escreva("Pode votar")
senao
    escreva("Não pode votar")
fimse

Fimalgoritmo