Algoritmo "questao5"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
nota: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe a nota: ")
leia(nota)

se nota >= 6 entao
   escreva("APROVADO")
senao
     escreva("REPROVADO")
fimse

Fimalgoritmo