Algoritmo "questao13"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
altura: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Altura: ")
leia(altura)

se altura > 1.8 entao
   escreva("Alto(a)", altura)
senao
    escreva("Baixo(a)", altura)
fimse

Fimalgoritmo