Algoritmo "questao8"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
salario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe o primeiro numero: ")
leia(salario)

se salario >= 2000 entao
   escreva("Salário Alto")
senao
     escreva("Salário Baixo")
fimse

Fimalgoritmo