Algoritmo "questao14"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
numero: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Numero: ")
leia(numero)

se numero % 5 = 0 entao
   escreva("Múltiplo de 5")
senao
    escreva("Não é múltiplo de 5")
fimse

Fimalgoritmo