Algoritmo "questao3"
// Disciplina   : Curso Back-end Python BFD
// Professor   : Glestiano
// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 22/08/2025
Var
// Seção de Declarações das variáveis
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe a idade: ")
leia(idade)

se idade > 17 entao
   escreva(idade, " é de maior")
senao
     escreva(idade, " é de menor")
fimse

Fimalgoritmo