Algoritmo "QUESTAO26"

// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 25/08/2025
Var
// Seção de Declarações das variáveis 
idade: inteiro
renda: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Idade: ")
leia(idade)
escreva("Renda: ")
leia(renda)

se (idade >= 21) e (renda >= 2000) entao
   escreva("Crédito APROVADO")
senao
     escreva("Crédito NÃO aprovado")
fimse

Fimalgoritmo