Algoritmo "QUESTAO28"

// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 25/08/2025
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe o número: ")
leia(num)

se (num >= 10) e (num <= 20) entao
   escreva("DENTRO DO INTERVALO")
senao
     escreva("FORA DO INTERVALO")
fimse

Fimalgoritmo