Algoritmo "QUESTAO23"

// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 25/08/2025
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe um número: ")
leia(num)

se (num > 100) ou (num = 50) entao
   escreva("PASSOU no teste")
senao
     escreva("NÃO passou no teste")
fimse

Fimalgoritmo