Algoritmo "QUESTAO24"

// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 25/08/2025
Var
// Seção de Declarações das variáveis 
num1, num2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe o primeiro número: ")
leia(num1)
escreva("Informe o segundo número: ")
leia(num2)

se nao(num1 % 2 = 0) e nao(num2 % 2 = 0) entao
   escreva("Os DOIS SÃO ÍMPARES")
senao
     escreva("Os dois NÃO são ÍMPARES")
fimse

Fimalgoritmo