Algoritmo "QUESTAO22"

// Autor(a)    : João Victor de Araújo Silva
// Data atual  : 25/08/2025
Var
// Seção de Declarações das variáveis 
temp: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Temperatura da cidade: ")
leia(temp)

se (temp >= 20) e (temp <= 30) entao
   escreva("Temperatura ideal")
senao
     escreva("Temperatura não ideal")
fimse

Fimalgoritmo